2025-08-15 14:26:24,842 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-15 14:26:24,843 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 10727, in etap_made
    flag = control_all_player_in_final(etap, all_sum_player_final) # проверяет все ли игроки распределены по финалам
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 10916, in control_all_player_in_final
    choice_gr_automat()
    ~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 7977, in choice_gr_automat
    player_in_table_group_and_write_Game_list_Result(stage)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 5760, in player_in_table_group_and_write_Game_list_Result
    table_made(pv, stage)
    ~~~~~~~~~~^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 12747, in table_made
    dict_table = tbl(stage, kg, ts, zagolovok, cW, rH)
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 12096, in tbl
    tdt_all = table_data(stage, kg)  # данные результатов в группах
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 14843, in table_data
    tdt_tmp = tdt_news(max_gamer, posev_data, count_player_group, tr, num_gr)
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 14882, in tdt_news
    tbl_tmp[i - 1][1] = fam
    ~~~~~~~^^^^^^^
IndexError: list index out of range
