2025-08-11 10:02:16,219 - ERROR - Необработанное исключение: TypeError: CharField.__init__() got multiple values for argument 'max_length'
2025-08-11 10:02:16,255 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 18271, in proba
    sex = CharField(Player, max_length=10, null=False)  # новый столбец, его поле и значение по умолчанию
TypeError: CharField.__init__() got multiple values for argument 'max_length'
