2025-08-03 12:02:26,390 - ERROR - Необработанное исключение: AttributeError: 'str' object has no attribute 'close'
2025-08-03 12:02:26,392 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 759, in log_file_read
    file_path.close()
    ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'close'
