2025-08-03 11:03:14,260 - ERROR - Необработанное исключение: AttributeError: 'str' object has no attribute 'getsize'
2025-08-03 11:03:14,262 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 757, in log_file_read
    file_size_bytes = parent_dir.getsize(f)
                      ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'getsize'
