2025-08-12 15:17:24,160 - ERROR - Необработанное исключение: AttributeError: type object 'Title' has no attribute 'sex'
2025-08-12 15:17:24,164 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 1049, in system_made
    system_competition()
    ~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 4745, in system_competition
    tit = Title.get((Title.id == title_id()) & (Title.sex == pol))
                                                ^^^^^^^^^
AttributeError: type object 'Title' has no attribute 'sex'
